name: Deploy .NET 8 B-Empleo-Dev to VPS

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH (OpenSSH key support)
        uses: webfactory/ssh-agent@v0.8.0

        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known_hosts
        run: ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -v ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} exit

      - name: Copy project in VPS
        run: |
          rsync -avz --exclude '.git' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:${{ secrets.VPS_DEPLOY_PATH }}

      - name: Deploy on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            cd ${{ secrets.VPS_DEPLOY_PATH }}/isc_bempleo_backend


            docker compose -f docker-compose.dev.yml down || true


            docker compose -f docker-compose.dev.yml up -d --build

           
          EOF
